### PR TITLE
Add LLVM releases for arm64

### PR DESCRIPTION
**Pull request by kulinseth**

### CODE REVIEW

**Comment by ptillet** [comment]
I think the current LLVM pin doesn't compile cleanly on macos, let me update it and hope it works better

**Comment by ptillet** [comment]
Should be good now if you rebase against `main`

**Comment by ptillet** [comment]
I think this needs to be rebased against `master`. Just updated the LLVM commit and now macos compiles properly

**Comment by kulinseth** [comment]
> I think this needs to be rebased against `main`. Just updated the LLVM commit and now macos compiles properly

Thanks, updated.

**Pull request merged**
